spring:
  application:
    # 服务名称
    name: mybcrm-service
  profiles:
    active: dev

server:
  # 服务端口
  port: 8081

eureka:
  client:
    service-url:
      # 服务注册中心地址
      defaultZone: http://localhost:8888/eureka/



#mybatis
mybatis:
  mapper-locations: classpath:com/ch/mybcrm/dao/mapper/*.xml
  config-location: classpath:mybatis-config.xml
